# Generated by Django 3.0.5 on 2020-05-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='serres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
    ]
